### ISSUE TITLE
Uncaught Range Error

### ISSUE THREAD

**Issue by miklb** [imdone/imdone-atom#207]
Attempting to load task board for project, finds number of files, and while parsing for tasks, it locks up and throws error `Uncaught RangeError: Maximum call stack size exceeded`

Atom then gives unresponsive error and closing is the only way to get back to the app, so can not copy full trace, posting screenshot of the app and error message.

Not this was taken with latest Atom Beta(1.14.0-beta2), however same behavior with latest stable (1.13.0).

Let me know if there's anything else I can provide.

![imdone_atom_time_out](https://cloud.githubusercontent.com/assets/819716/22273462/d6c79074-e26e-11e6-94d3-e6dfe47bf664.png)

**Comment by piascikj** [comment]
So it looks like you weren't able to get a stack trace.  What OS are you on?

**Comment by miklb** [comment]
Mac 10.12.3, but this was occurring before updating today.

**Comment by piascikj** [comment]
Really having a hard time figuring this one out.  Is this in a project you can grant me access to?  Have you tried other projects?

**Comment by miklb** [comment]
That was going to be next idea. I'm starting a new project based off the work in the repo I was having an issue with, so will try with a fresh project without a bunch of nested directories to see if I can narrow down the issue.

I really want to get this working and be able to use it.

**Comment by peterwilli** [comment]
I have the same problem on Ubuntu, blocks the GUI entirely, I also have big folders added to imdoneignore. It says that it's scanning 932 files.

**Comment by peterwilli** [comment]
I have the same issue, it says it's trying to scan 932 files. Here is my stack trace (snipped because it was unusually long)

```
RangeError: Maximum call stack size exceeded
    at Config.module.exports.Config.deepClone (/usr/share/atom/resources/app.asar/src/config.js:699:11)
    at /usr/share/atom/resources/app.asar/src/config.js:697:32
    at Object.mapObject (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:17)
    at Config.module.exports.Config.deepClone (/usr/share/atom/resources/app.asar/src/config.js:695:18)
    at Config.module.exports.Config.getRawValue (/usr/share/atom/resources/app.asar/src/config.js:591:22)
    at Config.module.exports.Config.get (/usr/share/atom/resources/app.asar/src/config.js:181:21)
    at Object.getSettings (/home/peter/.atom/packages/imdone-atom/lib/services/imdone-config.coffee:9:34)
    at Repository.imdoneRepo.shouldExclude (/home/peter/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:30:74)
    at Repository.repo.fileOK (/home/peter/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:14)
    at /home/peter/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:253:14
    at /home/peter/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/home/peter/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
   .......
```

**Comment by miklb** [comment]
@piascikj I tried with a new, small project and works like a charm, so definitely a problem with scanning a big project, ignores or not. Wondering if I can limit the scan to just TODO, as in my case, I don't see using any other tags.

**Comment by piascikj** [comment]
That's interesting.  How many files are there in your project folder?

Can you both run this command in your projects directory and send me the output?
```
find -maxdepth 1 -type d | while read -r dir; do printf "%s:\t" "$dir"; find "$dir" -type f | wc -l; done
```

**Comment by miklb** [comment]
```
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
Doesn't play nice in macOS

**Comment by piascikj** [comment]
I might have a fix for this.  Seems I'm trying to run a stat on up to 1024 files at one time.  Let me cut that back to about 256.

**Comment by piascikj** [comment]
ok, ready to go!  2.1.4 has the new limit.  Let me know how it works

**Comment by piascikj** [comment]
@peterwilli Thanks for the stack trace

**Comment by miklb** [comment]
OK, give me a minute. Need to sign up for paid account 😉

**Comment by miklb** [comment]
No dice. Same call stack size error and locking up.

**Comment by piascikj** [comment]
ok, were you able to get a stack trace?

**Comment by miklb** [comment]
It's huge, but this seems to be the relevant part (almost like it repeats in the trace…)
```
RangeError: Maximum call stack size exceeded
    at Config.module.exports.Config.deepClone (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:699:11)
    at Config.module.exports.Config.getRawValue (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:591:22)
    at Config.module.exports.Config.get (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:181:21)
    at Object.getSettings (/Users/miklb/.atom/packages/imdone-atom/lib/services/imdone-config.coffee:9:34)
    at Repository.imdoneRepo.shouldExclude (/Users/miklb/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:30:74)
    at Repository.repo.fileOK (/Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:14)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:253:14
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:273:11
```

**Comment by piascikj** [comment]
Try 2.1.15.  I reduced the async limit to 10.  If that doesn't work, I have a couple more things to try.  

['Maximum call stack size exceeded' using async.forEachLimit · Issue #75 · caolan/async](https://github.com/caolan/async/issues/75)

Or maybe we can do a live debug session later.  I have to run out to the grocery.

**Comment by miklb** [comment]
Related #78

**Comment by miklb** [comment]
```
RangeError: Maximum call stack size exceeded
    at Config.module.exports.Config.deepClone (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:699:11)
    at Config.module.exports.Config.getRawValue (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:591:22)
    at Config.module.exports.Config.get (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:181:21)
    at Object.getSettings (/Users/miklb/.atom/packages/imdone-atom/lib/services/imdone-config.coffee:9:34)
    at Repository.imdoneRepo.shouldExclude (/Users/miklb/.atom/packages/imdone-atom/lib/services/imdone-helper.coffee:30:74)
    at Repository.repo.fileOK (/Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:14)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:253:14
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:273:11
```
End
```
    at Repository.repo.fileOK (/Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:42)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:253:14
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:273:11
    at Repository.repo.fileOK (/Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:108:42)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:253:14
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:181:20
    at replenish (/Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:319:21)
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:326:29
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/async/lib/async.js:44:16
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:273:11
    at /Users/miklb/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:115:51
    at FSReqWrap.oncomplete (fs.js:123:15)
```
2.1.15

**Comment by piascikj** [comment]
OK, I fixed up the error handling on the isBinary check in [imdone-core/repo-fs-store.js](https://github.com/imdone/imdone-core/blob/master/lib/mixins/repo-fs-store.js#L115).  It's now async and just returning false on error.  Give 2.1.16 a try and let me know what happens.  Thanks for your business @miklb!

**Comment by miklb** [comment]
Unfortunately that didn't resolve the issue. This particular project has a lot of binary files and isn't a priority. I've actually spun out the part that I'm working on into a new repo and it works fine there.

Going forward, I will watch bigger projects and perhaps getting ahead of all of non-code elements in the ignore files will help.

Unfortunately, it's a private repo that I wouldn't have opportunity to share access. I appreciate your work on it, hopefully the fixes will help others experiencing the error.

**Comment by piascikj** [comment]
ok, that sounds like a good idea.  I'll also try testing with more binary files.

**Comment by piascikj** [comment]
I just published another release to simplify the binary check.  Let me know if it helps.  This one is tough for me, since I'm unable to reproduce it.

**Comment by UtamaruMonster** [comment]
Same problem:
Big project, error on config.js:699.
Atom: 1.14.1
OS: macOS 10.12.3
imdone-atom: 2.1.18
event if i use .imdoneignore, finds 8 files but same error

**Comment by peterwilli** [comment]
@piascikj I just updated to the latest imdone and atom version on Ubuntu, it gives me the same error, it seems. I added 2 shots so you can tell by yourself.

I'm interested in why you can't reproduce, what kind of system are you running? I'm using Ubuntu with SSD which should be fast enough to can 600+ files.
![screenshot from 2017-02-15 16 55 18](https://cloud.githubusercontent.com/assets/1212814/22982520/b89d2d7e-f39f-11e6-8a0a-6d688477b47f.png)
![screenshot from 2017-02-15 16 55 28](https://cloud.githubusercontent.com/assets/1212814/22982519/b88535ac-f39f-11e6-8cdc-fbfbef29138b.png)

**Comment by mhnavarro** [comment]
Default config make the app crash, the exclude paths in config.json are not working.
In my case using .imdoneignore and adding the excluded folders to it, made the package works at least

**Comment by piascikj** [comment]
Anyone experiencing the range error please try 2.1.20 and let me know if you're still experiencing the issue.  If you are, please attach a fresh stack trace.

**Comment by piascikj** [comment]
Try v2.1.21. I filtered the files before calling async.each. I think it's fixed.

**Comment by peterwilli** [comment]
@piascikj thanks, it works over here! :+1:
