### ISSUE TITLE
Bug still exists: "Failed to activate the imdone-atom package"

### ISSUE THREAD

**Issue by aubergine10** [imdone/imdone-atom#393]
The original issue is closed and being ignored, despite users still having the issue:

https://github.com/imdone/imdone-atom/issues/58

**Comment by piascikj** [comment]
@aubergine10 This should be fixed with [this commit](https://github.com/imdone/imdone-atom/commit/bd973db62c9b6965c66a6e0d003cb50455f1aece)

**Comment by aubergine10** [comment]
Confirmed fixed :)

**Comment by emilioluque** [comment]
I still get it:
Unexpected token ,
Hide Stack Trace
SyntaxError: Unexpected token ,
    at Module.get_Module._compile (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:146949)
    at Object.value [as .js] (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/emili/AppData/Local/atom/app-1.38.1/resources/app.asar/static/index.js:60:45)
    at require (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:146462)
    at Object.<anonymous> (C:\Users\emili\.atom\packages\imdone-atom\node_modules\keen-tracking\lib\server.js:7:24)
    at Object.<anonymous> (C:\Users\emili\.atom\packages\imdone-atom\node_modules\keen-tracking\lib\server.js:34:3)
    at Module.get_Module._compile (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:147172)
    at Object.value [as .js] (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/emili/AppData/Local/atom/app-1.38.1/resources/app.asar/static/index.js:60:45)
    at require (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:146462)
    at Object.<anonymous> (C:\Users\emili\.atom\packages\imdone-atom\lib\services\track.js:1:175)
    at Object.<anonymous> (C:\Users\emili\.atom\packages\imdone-atom\lib\services\track.js:23:3)
    at Module.get_Module._compile (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:147172)
    at Object.value [as .js] (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/emili/AppData/Local/atom/app-1.38.1/resources/app.asar/static/index.js:60:45)
    at require (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:146462)
    at Object.<anonymous> (file:///C:/Users/emili/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:3:9)
    at Object.<anonymous> (file:///C:/Users/emili/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/emili/.atom/packages/imdone-atom/lib/views/imdone-atom-view.coffee:1:1)
    at Module.get_Module._compile (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:147172)
    at Object.value [as .coffee] (C:\Users\emili\AppData\Local\atom\app-1.38.1\resources\app\static\<embedded>:11:150720)
