### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by srissel** [imdone/imdone-atom#7]
Steps to reproduce:
1. Added TODO-Task in a file: "// TODO: foo bar"
2. Right-clicked on this file in Atom's tree and chose "show Tasks - iMIDone"
3. New file tab "Template Issues" opened, with content
   "Loading template Issues.
   It's gonna be legen... wait for it."

**Atom Version**: 1.0.5
**System**: BTXNB40
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.10
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\srissel\.atom\packages\imdone-atom\lib\imdone-atom-view.coffee:44

TypeError: Cannot read property 'length' of undefined
  at C:\Users\srissel\.atom\packages\imdone-atom\lib\imdone-atom-view.coffee:44:15
  at C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:62:46
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
     -3:36.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -3:31.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:29.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -3:28.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:27.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:27.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:27.3.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -3:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:56.4.0 ctrl-last-tab:next (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -1:36.8.0 expose:toggle (div.settings-view.pane-item)
     -0:35.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:24.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
compare-files, v0.6.2
ctrl-last-tab, v0.2.0
expose, v0.4.0
highlight-selected, v0.10.1
imdone-atom, v1.1.10
language-groovy, v0.4.0
pretty-json, v0.4.1
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by filipesilva** [comment]
Same.

**Comment by piascikj** [comment]
Fixed by modifying uri with encodeURIComponent

**Comment by piascikj** [comment]
It seems this issue is produced when no files are open in atom.

**Comment by Lewiscowles1986** [comment]
Sorry @piascikj but I have files open, and it's still happening to me on win8.1

**Comment by Lewiscowles1986** [comment]
Thanks for re-opening, I had one file open

[Enter steps to reproduce below:]

1. Open Atom with file
2. press `Alt`+`T`

**Note:** it looks like launching from the settings pane at all also does this regardless of open files. I'm pretty sure if you ` || ''` (if array required then `.split()`) in js, then it will get rid of the length issue

**Atom Version**: 1.4.3
**System**: Microsoft Windows 8.1
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /C:/Users/Lewis/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:204

TypeError: Cannot read property 'length' of undefined
    at file:///C:/Users/Lewis/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:86:24
    at C:\Users\Lewis\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:82:46
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -2:11.8.0 java-generator:generate-to-string (atom-text-editor.editor.is-focused)
     -1:38.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  8x -1:14.4.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
  3x -0:48.6.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:47.4.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:43.6.0 java-generator:generate-to-string (atom-text-editor.editor.is-focused)
  2x -0:33 imdone-atom:tasks (atom-text-editor.editor.is-focused)
  2x -0:31.1.0 java-generator:generate-to-string (atom-text-editor.editor.is-focused)
     -0:27.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
  2x -0:15.5.0 imdone-atom:todays-journal (atom-text-editor.editor.is-focused)
  3x -0:08.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
bottom-dock, v0.3.7
color-picker, v2.1.1
genrandom, v0.3.0
gradle-manager, v0.0.5
imdone-atom, v1.3.25
java-generator, v2.1.1
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by Lewiscowles1986** [comment]
The strangeness is that it reports to be from activate power mode, when it is clearly not...

**Comment by piascikj** [comment]
Is this still an issue?

**Comment by Lewiscowles1986** [comment]
I don't use Imdone anymore, nearly 2 year old issue so I hope it's not.

**Comment by setalosas** [comment]
This is definitely still an issue.

![image](https://user-images.githubusercontent.com/21111643/43372509-df70e064-93a1-11e8-89c3-6d55ecf92e56.png)
